/*
-- Query: SELECT * FROM banka_backup.prenos
LIMIT 0, 1000

-- Date: 2022-02-25 02:41
*/
INSERT INTO `` (`IDTra`,`IDRacNA`) VALUES (9,1);
INSERT INTO `` (`IDTra`,`IDRacNA`) VALUES (25,1);
INSERT INTO `` (`IDTra`,`IDRacNA`) VALUES (21,2);
INSERT INTO `` (`IDTra`,`IDRacNA`) VALUES (34,2);
INSERT INTO `` (`IDTra`,`IDRacNA`) VALUES (15,3);
INSERT INTO `` (`IDTra`,`IDRacNA`) VALUES (19,3);
INSERT INTO `` (`IDTra`,`IDRacNA`) VALUES (27,5);
INSERT INTO `` (`IDTra`,`IDRacNA`) VALUES (32,6);
INSERT INTO `` (`IDTra`,`IDRacNA`) VALUES (5,8);
INSERT INTO `` (`IDTra`,`IDRacNA`) VALUES (7,8);
INSERT INTO `` (`IDTra`,`IDRacNA`) VALUES (23,12);
